define my_asn = 65000;
define my_ip4 = 10.0.0.2;
define my_ip6 = fd0a::2;

define my_com4 = 4;
define my_com6 = 6;

define my_geo = 900;
define geo_asn = 65001;

#define host_ip4 = 10.0.0.1;
#define host_ip6 = fd0a::1;

define no_rt4 = [
	10.0.0.0/8+,
	100.64.0.0/10+,
	127.0.0.0/8+,
	169.254.0.0/16+,
	172.16.0.0/12+,
	192.168.0.0/16+
];

define no_rt6 = [
	::1/128,
	fc00::/7+,
	fe80::/10+
];

router id my_ip4;

log "/var/log/bird.log" all;

#protocol bfd b0 {
#    interface "eth*", "veth*" {
#        min rx interval 1000 ms;
#        min tx interval 1000 ms;
#    };
#}

protocol device d0 {
}

protocol kernel k4 {
	ipv4 {
		import none;
		export none;
	};
}

protocol kernel k6 {
	ipv6 {
		import none;
		export none;
	};
}

include "/etc/bird/bird.conf.d/*.proto.*.conf";

protocol static s4 {
	description "Generic Static IPv4";
	ipv4 {
		import filter {
			bgp_community.add((my_asn, my_com4));
			bgp_community.add((my_asn, 0));
			accept;
		};
		export none;
	};
	include "/etc/bird/bird.conf.d/*.ipv4.static.conf";
}

protocol static s6 {
	description "Generic Static IPv6";
	ipv6 {
		import filter {
			bgp_community.add((my_asn, my_com6));
			bgp_community.add((my_asn, 0));
			accept;
		};
		export none;
	};
	include "/etc/bird/bird.conf.d/*.ipv6.static.conf";
}

filter rt4_export {
	if source != RTS_STATIC then reject;
	if net ~ no_rt4 then reject;
	include "/etc/bird/bird.conf.d/*.export.filter.conf";
	accept;
}

filter rt6_export {
	if source != RTS_STATIC then reject;
	if net ~ no_rt6 then reject;
	include "/etc/bird/bird.conf.d/*.export.filter.conf";
	accept;
}

template bgp bgp4_tpl {
    local as my_asn;
    ipv4 { 
        import none;
        export filter rt4_export;
    };
}

template bgp bgp6_tpl {
    local as my_asn;
    ipv6 { 
        import none;
        export filter rt6_export;
    };
}

protocol bgp bgp4_any from bgp4_tpl {
	dynamic name "bgp_peer";
	passive on;
	multihop;
	neighbor range 0.0.0.0/0 external;
}

protocol bgp bgp6_any from bgp6_tpl {
	dynamic name "bgp_peer";
	passive on;
	multihop;
	neighbor range ::/0 external;
}

#protocol bgp bgp4_host from bgp4_tpl {
#    bfd on;
#    direct;
#    neighbor host_ip4 external;
#}

#protocol bgp bgp6_host from bgp6_tpl {
#    bfd on;
#    direct;
#    neighbor host_ip6 external;
#}
